"use client"
import type { Metadata } from "next";
import { useRouter } from "next/router"
import { Inter } from "next/font/google";
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar'

import { SidebarContext } from '@/context/SidebarContext'
import React, {
  useContext, useEffect,
  useMemo
} from 'react';

// import { useUserContext } from '@/context/userContext';
import { AUTH_WHITE_LIST } from "@/utils/const";
import { useLocalStorage } from "@/hooks/useLocalStorage";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { store } = useUserContext()
  const { getLocal } = useLocalStorage();
  const { isSidebarOpen, closeSidebar } = useContext(SidebarContext)
  const router = useRouter()
  useEffect(() => {
    closeSidebar()
  }, [])

  const isCurAuthwhiteRoute = useMemo(() => {
    return AUTH_WHITE_LIST.includes(router.pathname)
  }, [router])

  useEffect(() => {
    if (router.isReady) {
      const token = getLocal('userInfo')?.token

      if (!token && !isCurAuthwhiteRoute) {
        router.replace('/login')
      }

      if (token && isCurAuthwhiteRoute) {
        router.push('/')
      }
    }
  }, [router.isReady, router])


  return (
    <div
      className={`flex h-screen bg-gray-50 dark:bg-gray-900  ${isSidebarOpen && 'overflow-hidden'}`}
    >
      {/* <div > */}
      {!isCurAuthwhiteRoute && <Sidebar />}
      {/* </div> */}
      <div className="flex flex-col flex-1 w-full">

        <Header style={{ display: !isCurAuthwhiteRoute ? 'block' : 'none' }}></Header>
        <main className="h-full overflow-y-auto scroll-smooth relative">
          <div className=" grid p-14 max-md:p-8 py-6 mx-auto">{children}</div>
        </main>
      </div>
    </div>
  );
}

