"use client"
import type { Metadata } from "next";
import { useRouter } from "next/router"
import { Inter } from "next/font/google";
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar'
import { SidebarContext } from '@/context/SidebarContext'
import React, {
  useContext, useEffect
} from 'react';

import { useUserContext } from '@/context/userContext';


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { store } = useUserContext()
  const { isSidebarOpen, closeSidebar } = useContext(SidebarContext)
  const router = useRouter()
  useEffect(() => {
    closeSidebar()
  }, [])


  return (
    <div
      className={`flex h-screen bg-gray-50 dark:bg-gray-900  ${isSidebarOpen && 'overflow-hidden'}`}
    >
      {/* <div > */}
      {store?.id && <Sidebar />}
      {/* </div> */}
      <div className="flex flex-col flex-1 w-full">

        <Header style={{ display: store?.id ? 'block' : 'none' }}></Header>
        <main className="h-full overflow-y-auto scroll-smooth">
          <div className="container grid px-6 mx-auto">{children}</div>
        </main>
      </div>
    </div>
  );
}
